"""Parity checks between FieldSampler and NBodySampler executors.

Both engines should produce equivalent dynamics on static-PDE worlds
(``temporal_order = 0``) up to integrator + grid noise.  These tests
exist because the N-body pairwise force law historically multiplied the
two charge arrays symmetrically (``F ∝ q_i · q_j``), which silently:

* zeroed out forces on probes (``q = 0``) — they coasted in straight lines,
* over-amplified self-interactions of high-coupling species (Species B
  with ``q = 3`` saw a B↔B force ``9×`` too strong; dark matter with
  ``q = 5`` was ``25×`` too strong inside the halo).

The fix is to track two independent arrays — ``source_charges`` (how
strongly a particle generates the field) and ``force_charges`` (how
strongly it responds) — exactly like ``FieldSampler.source_coupling``
and ``FieldSampler.particle_force``.  These tests assert the bug stays
fixed.
"""

import numpy as np
import pytest

from physchool.worlds.nbody_sampler import NBodySampler
from physchool.worlds.force_laws import poisson_2d_force, poisson_2d_potential
from scienceagent.executor import (
    DarkMatterExecutor, NBodyDarkMatterExecutor,
    NBodyThreeSpeciesExecutor,
    SpeciesExecutor, NBodySpeciesExecutor,
)


# ──────────────────────────────────────────────────────────────────────────
# Direct-N-body parity: probes feel forces, dark matter drift agrees with field
# ──────────────────────────────────────────────────────────────────────────

def _dark_matter_exp():
    return {
        "probe_positions":  [[5.0, 0.0], [0.0, 5.0], [-5.0, 0.0],
                             [0.0, -5.0], [7.0, 7.0]],
        "probe_velocities": [[0.0, 0.0]] * 5,
        "measurement_times": [1.0, 2.0, 3.0, 5.0],
    }


class TestProbesFeelForces:
    """Regression: probes have ``source_charge = 0`` but should still feel
    the field generated by visible + dark sources."""

    def test_dark_matter_probes_drift(self):
        res = NBodyDarkMatterExecutor().run([_dark_matter_exp()])[0]
        pos0 = np.array(res["positions"][0])
        posT = np.array(res["positions"][-1])
        # Agent-facing layout is [visible (0–19), probes (20–24)].
        probe_drift = np.linalg.norm(posT[20:25] - pos0[20:25], axis=1)
        assert probe_drift.min() > 0.5, (
            f"All N-body probes drifted < 0.5 length units after 5 t.u. "
            f"(min drift {probe_drift.min():.3e}); the engine is applying "
            "zero force to neutral probes — the source/force charge "
            "convention has regressed.")

    def test_three_species_probes_drift(self):
        exp = {
            "probe_positions":  [[5.0, 0.0], [0.0, 5.0], [-5.0, 0.0],
                                 [0.0, -5.0], [7.0, 7.0]],
            "probe_velocities": [[0.0, 0.0]] * 5,
            "measurement_times": [1.0, 2.0, 3.0],
        }
        res = NBodyThreeSpeciesExecutor().run([exp])[0]
        pos = np.array(res["positions"])  # (T, 35, 2) — full output
        probe_drift = np.linalg.norm(pos[-1, 30:35] - pos[0, 30:35], axis=1)
        assert probe_drift.min() > 1e-3, (
            f"Three-species N-body probes drifted < 1e-3 (min "
            f"{probe_drift.min():.3e}); neutral probes are getting zero force.")


class TestEngineParity:
    """N-body trajectories should track the field engine to within
    integrator + CIC/grid tolerance.  Pre-fix, dark-matter drift was
    ~5× higher than field-engine ground truth."""

    def test_dark_matter_drift_matches_field(self):
        exp = _dark_matter_exp()
        field_full = DarkMatterExecutor().run_full([exp])[0]
        nbody_full = NBodyDarkMatterExecutor().run_full([exp])[0]
        f = np.asarray(field_full["positions"])
        n = np.asarray(nbody_full["positions"])

        # Dark matter occupies sim indices 20–29 in both engines.
        f_dark = np.linalg.norm(f[-1, 20:30] - f[0, 20:30], axis=1).mean()
        n_dark = np.linalg.norm(n[-1, 20:30] - n[0, 20:30], axis=1).mean()
        # Pre-fix this returned ~5x; post-fix the two engines agree to
        # well within the integrator + grid noise.  Use a generous 50%
        # tolerance to keep the test stable across grid resolutions.
        assert n_dark == pytest.approx(f_dark, rel=0.5), (
            f"Dark-matter drift mismatch: field={f_dark:.3f}, "
            f"nbody={n_dark:.3f}.  Pre-fix ratio was ~5×.")

    def test_dark_matter_probe_drift_matches_field(self):
        exp = _dark_matter_exp()
        f = np.asarray(DarkMatterExecutor().run([exp])[0]["positions"])
        n = np.asarray(NBodyDarkMatterExecutor().run([exp])[0]["positions"])

        # Agent-facing probe slice is 20:25.
        f_probe = np.linalg.norm(f[-1, 20:25] - f[0, 20:25], axis=1)
        n_probe = np.linalg.norm(n[-1, 20:25] - n[0, 20:25], axis=1)

        rel_err = np.abs(f_probe - n_probe) / np.maximum(f_probe, 1e-6)
        assert rel_err.max() < 0.5, (
            f"Probe drift mismatch field vs nbody (rel err {rel_err}): "
            f"field={f_probe}, nbody={n_probe}")

    def test_species_engine_parity(self):
        """Species B (q = 3) should feel itself with the same 1/r law as
        Species A (q = 1) — pre-fix, B–B forces were 9× too strong."""
        exp = {
            "positions":  [[2.0, 0.0], [-2.0, 0.0], [0.0, 2.0],
                           [0.0, -2.0], [3.0, 3.0], [-3.0, -3.0]],
            "velocities": [[0.0, 0.0]] * 6,
            "measurement_times": [0.5, 1.0, 1.5, 2.0],
        }
        f = np.asarray(SpeciesExecutor().run([exp])[0]["positions"])
        n = np.asarray(NBodySpeciesExecutor().run([exp])[0]["positions"])
        # Per-particle final-position error.  CIC+FFT vs direct N-body
        # disagree at ~5–15% near close encounters, so we allow 0.6 length
        # units of slack at t = 2.0 with default softening.
        final_err = np.linalg.norm(f[-1] - n[-1], axis=1)
        assert final_err.max() < 0.6, (
            f"Per-particle position error at t=2.0 too large: {final_err}; "
            "field/nbody divergence indicates a pairwise charge bug.")


# ──────────────────────────────────────────────────────────────────────────
# Direct unit tests on the asymmetric pairwise convention
# ──────────────────────────────────────────────────────────────────────────

def _build_pair_sim(source, force, masses=None, sep=4.0, softening=0.0):
    """Two-particle test rig: particles at (±sep/2, 0), zero velocity."""
    masses = np.ones(2) if masses is None else np.asarray(masses, dtype=np.float64)
    positions = np.array([[-sep / 2, 0.0], [+sep / 2, 0.0]], dtype=np.float64)
    velocities = np.zeros_like(positions)
    return NBodySampler(
        masses=masses,
        source_charges=np.asarray(source, dtype=np.float64),
        force_charges=np.asarray(force, dtype=np.float64),
        initial_positions=positions, initial_velocities=velocities,
        force_law=poisson_2d_force, potential_law=poisson_2d_potential,
        integrator="leapfrog", dt=1e-3, softening=softening,
        spatial_dimensions=2,
    )


def _initial_accel(sim):
    """Return the acceleration array at the simulator's initial state."""
    accel_fn = sim._accel_fn
    return np.asarray(
        accel_fn(sim.positions, sim.source_charges,
                 sim.force_charges, sim.masses)
    )


class TestPairwiseConvention:
    """Unit tests on the asymmetric pairwise force convention."""

    def test_zero_force_charge_means_no_acceleration(self):
        """A receiver with ``force_charge = 0`` must have zero acceleration
        even though its source_charge is non-zero."""
        sim = _build_pair_sim(source=[1.0, 1.0], force=[1.0, 0.0])
        a = _initial_accel(sim)
        assert np.linalg.norm(a[1]) < 1e-12, (
            f"force_charge=0 receiver got nonzero acceleration {a[1]}")
        # The other particle still feels the field.
        assert np.linalg.norm(a[0]) > 1e-6

    def test_zero_source_charge_pulls_no_one(self):
        """A particle with ``source_charge = 0`` (a probe) generates no
        field, so its non-zero ``force_charge`` partner feels nothing."""
        sim = _build_pair_sim(source=[1.0, 0.0], force=[1.0, 1.0])
        a = _initial_accel(sim)
        # Particle 0 (responder=1) should feel nothing from a probe (source=0).
        assert np.linalg.norm(a[0]) < 1e-12, (
            f"Particle 0 saw force from a source=0 partner: a={a[0]}")
        # The probe itself (source=0, force=1) feels particle 0's field.
        assert np.linalg.norm(a[1]) > 1e-6

    def test_b_internal_force_is_3x_a_internal_not_9x(self):
        """Two B particles (source=3) sourcing each other should produce
        an acceleration 3× larger than two A particles (source=1) — the
        pre-fix convention gave 9× because both sides multiplied by q."""
        a_sim = _build_pair_sim(source=[1.0, 1.0], force=[1.0, 1.0])
        b_sim = _build_pair_sim(source=[3.0, 3.0], force=[1.0, 1.0])
        a_mag = np.linalg.norm(_initial_accel(a_sim)[0])
        b_mag = np.linalg.norm(_initial_accel(b_sim)[0])
        ratio = b_mag / a_mag
        assert ratio == pytest.approx(3.0, rel=1e-9), (
            f"B–B / A–A acceleration ratio is {ratio:.4f}, expected 3.0 "
            f"(pre-fix bug gave 9.0).")

    def test_legacy_charges_alias_still_works(self):
        """Passing the old ``charges=`` argument should keep the
        gravitational convention (source = force) intact."""
        sim_new = _build_pair_sim(source=[2.0, 2.0], force=[2.0, 2.0])
        sim_legacy = NBodySampler(
            masses=np.ones(2),
            charges=np.array([2.0, 2.0]),
            initial_positions=np.array([[-2.0, 0.0], [2.0, 0.0]]),
            initial_velocities=np.zeros((2, 2)),
            force_law=poisson_2d_force, potential_law=poisson_2d_potential,
            integrator="leapfrog", dt=1e-3, softening=0.0,
            spatial_dimensions=2,
        )
        a_new = _initial_accel(sim_new)
        a_leg = _initial_accel(sim_legacy)
        np.testing.assert_allclose(a_new, a_leg, rtol=1e-12, atol=1e-12)


class TestAPIValidation:
    """Argument validation in NBodySampler.__init__."""

    def test_partial_split_args_rejected(self):
        with pytest.raises(ValueError, match="both"):
            NBodySampler(
                masses=np.ones(2), source_charges=np.ones(2),
                initial_positions=np.zeros((2, 2)),
                initial_velocities=np.zeros((2, 2)),
                force_law=poisson_2d_force,
                spatial_dimensions=2,
            )

    def test_split_and_legacy_rejected_together(self):
        with pytest.raises(ValueError, match="pick one"):
            NBodySampler(
                masses=np.ones(2),
                charges=np.ones(2),
                source_charges=np.ones(2), force_charges=np.ones(2),
                initial_positions=np.zeros((2, 2)),
                initial_velocities=np.zeros((2, 2)),
                force_law=poisson_2d_force,
                spatial_dimensions=2,
            )

    def test_charge_shape_mismatch_rejected(self):
        with pytest.raises(ValueError, match="same shape"):
            NBodySampler(
                masses=np.ones(2),
                source_charges=np.ones(3), force_charges=np.ones(2),
                initial_positions=np.zeros((2, 2)),
                initial_velocities=np.zeros((2, 2)),
                force_law=poisson_2d_force,
                spatial_dimensions=2,
            )
